### PR TITLE
Ft enable social logins 147322117

### PR DESCRIPTION
**Pull request by kevintumbo**
#### What does this PR do?
Enable social logins - Facebook, Twitter, Google

#### Description of Task to be completed?
Allow a new user to login with their pre-existing social media account. 
specifically Facebook, Twitter, Google-plus and Github

#### How should this be manually tested?
 run your server :python manage.py run server
click on any of the social network buttons to log in.

#### What are the relevant pivotal tracker stories?
147322117

#### Screenshots (if appropriate)
screen shot 2017-06-23 at 15 47 58

### CODE REVIEW

**Comment by andela-sjames** [comment]
Can we fix the errors for next PR's

**Comment by andela-sjames** [comment]
```======================================================================
FAIL: test_register (wger.core.tests.test_registration.RegistrationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/andela/wger_asgardians/wger/core/tests/test_registration.py", line 76, in test_register
    self.assertEqual(response.status_code, 302)
AssertionError: 200 != 302
----------------------------------------------------------------------
Ran 1093 tests in 316.767s```

**Comment by andela-sjames** [comment]
Status update here

**Comment by kevintumbo** [comment]
fixed conflicts

**Comment by andela-sjames** [comment]
Is this passing on Travis yet? @kevintumbo

**Comment by kevintumbo** [comment]
currently building ....Large number of tests making the build take a while

**Pull request merged**
