### PR TITLE
Ft heroku deployment 147322077

### PR DESCRIPTION
**Pull request by WNjihia**
#### What does this PR do?
Deploy the wger application to Heroku
#### How should this be manually tested?
```
Visit the site: https://git.heroku.com/wger-asgardians.git
```
### Additional information
To successfully deploy to Heroku, the following buildpacks are added to the Heroku settings:
```
heroku/nodejs
https://github.com/WNjihia/wger-buildpack-python
```

### CODE REVIEW

**Comment by andela-sjames** [comment]
What is the status of this?

**Comment by andela-sjames** [comment]
Status update here

**Comment by andela-sjames** [comment]
@WNjihia why is this branch still not up to date with develop?

**Comment by WNjihia** [comment]
@andela-sjames I have updated this branch, kindly review it

**Pull request merged**
