### PR TITLE
Ft coveralls travisci integration 147322077

### PR DESCRIPTION
**Pull request by kevintumbo**
#### What does this PR do?
Setup slack integrations for Github, Pivotal tracker, Travis CI
#### Description of Task to be completed?
Integrate slack to receive notifications when anything happens in Github, pivotal tracker, travis CI an coveralls 

#### How should this be manually tested?
write a comment in pivotal traker, github
push some work to recieve pivotal Tracker notifications

#### What are the relevant pivotal tracker stories?
147322073

#### Screenshots (if appropriate)
screen shot 2017-06-23 at 16 44 43

### CODE REVIEW

**Comment by andela-sjames** [comment]
Status update here...

**Comment by kevintumbo** [comment]
fixed the merge conflict

**Comment by andela-sjames** [comment]
Please confirm that this branch is up to date with develop branch @kevintumbo

**Comment by kevintumbo** [comment]
confirmed...Branch is up to date

**Pull request merged**
