### PR TITLE
Ft detailed exercise 147322083

### PR DESCRIPTION
**Pull request by WNjihia**
#### What does this PR do?
Create a new read-only API endpoint that collects information on exercises.
#### Description of Task to be completed?
Create a new read-only API endpoint that collects all the information of an exercise such as muscles, category, images, etc. This makes it easier for clients to get all the info since only a single request is needed to be done
#### Screenshots
screen shot 2017-06-29 at 18 02 48

### CODE REVIEW

**Comment by andela-sjames** [comment]
@WNjihia please rebase with develop on this

**Comment by andela-sjames** [comment]
Why do you have 296 files changed on this branch hard for me to see what you have done here, can your commits be more specific to your changes only.

**Comment by andela-sjames** [comment]
Seems like this branch has the commits of other branches, this should not be the case you should use `git checkout -b <new_branch_name>` and rebase properly to fix this.

**Comment by andela-sjames** [comment]
@WNjihia why have you not responded to my previous message?

**Comment by WNjihia** [comment]
Okay I will create a new branch and rebase

**Pull request closed without merging**
